config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#root'
  
  namespace :api, defaults: {format: :json} do
    resources :users, only: [:create, :update, :show]
    resource :session, only: [:create, :destroy]
    resources :scripts
    get "/session/guestlogin", to: "sessions#create_guest_session"
    get "/search", to: "searchs#search"
  end

  get "/install/:id.user.:format", to: "pages#install_script"
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-stuff">
          <span class="sr-only">Toggle Navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">MonkeyScripts</a>
      </div>
    
      <div class="collapse navbar-collapse" id="navbar-stuff">
        <ul class="nav navbar-nav navbar-right">
          <li class="monkey-search-wrapper">
            <input class="monkey-search" type="text"></input>
            <div id="live-results"></div>
          </li>
          <li>
            <a id="search-button" href title="Search">
              <span class="glyphicon glyphicon-search"></span>
            </a>
          </li>
          <li>
            <a id="question-button" href title="What is all of this?"
               data-toggle="modal" data-target="#info-modal">
              <span class="glyphicon glyphicon-question-sign"></span>
            </a>
          </li>
          <% unless current_user %>
            <li>
              <a href data-toggle="modal" data-target="#login-modal">Login</a>
            </li>
            <li>
              <a href id="guest-login">Guest</a>
            </li>
            <li>
              <a href data-toggle="modal" data-target="#signup-modal">Join Us</a>
            </li>
          <% else %>
            <li>
              <a href="#/script/new" title="Create new script">
                <span class="glyphicon glyphicon-plus"></span>
              </a>
            </li>
            <li class="dropdown">
              <a href="javascript:void(0);" 
                 class="dropdown-toggle" 
                 data-toggle="dropdown">
                <%= current_user.username %><span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to "My Profile", "#/profile/"+current_user.id.to_s -%>
                </li>
                <li><a href id="logout-button">Log Out</a></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

<%= render partial: "layouts/login_modals" %>
<%= render partial: "layouts/info_modal" %>

app/views/layouts/_info_modal.html.erb
<div class="modal fade" id="info-modal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;<span class="sr-only">Close</span></button>
        <h4 class="modal-title">What are Userscripts and how do you use them?</hr>
      </div>
      
      <div class="modal-body">
        <div class="row info-about">
          <h3>What are userscripts?</h3>
          <p>Userscripts are cross-browser scripts that extend browser and website functionality. Examples can range anywhere from changing the design of your favorite website to automating processes. Userscripts are light-weight browser extensions you can add and edit on the fly.</p>
        </div>
        <div class="row info-download">
          <h3>How do I use them?</h3>
          <p>First you must install your browser's userscript manager. Click on the icon below that corresponds with the browser you use.</p>

          <div class="info-browser-links">
            <div class="row">
              <div class="col-md-4">
                <a href="https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/"
                   target="_blank">
                  <img src="<%= image_path("firefox-128.png") %>"/>
                </a>
              </div>
              <div class="col-md-4">
                <a href="https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en"
                   target="_blank">
                  <img src="<%= image_path("chrome-128.png") %>"/>
                </a>
              </div>
              <div class="col-md-4">
                <a href="https://addons.opera.com/en/extensions/details/tampermonkey-beta/?display=en"
                   target="_blank">
                  <img src="<%= image_path("opera-128.png") %>"/>
                </a>
              </div>
            </div>
            <i>Unfortunately there are no stable userscript managers for IE or Safari at this time.</i>
          </div>
          
          <p>Once you have installed the manager, find the userscript you want and select the Download option. The manager will take care of the rest!</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_login_modals.html.erb
<div class="modal fade" id="login-modal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;<span class="sr-only">Close</span></button>
        <h4 class="modal-title">Welcome back! Let's log you in...</hr>
      </div>
      
      <div class="modal-body">
        
        <form action="<%= api_session_url %>" id="login-form" method="POST">
          <div class="form-alert"></div>
          <input type="hidden" 
                 name="authenticity_token" 
                 value="<%= form_authenticity_token %>">
                 
          <div class="form-group">
            <label for="email">Email</label>
            <input type="text"
                   class="form-control"
                   id="email"
                   name="session[email]"
                   tabindex="1">
          </div>
          
          <div class="form-group">
            <label for="password">Password</label>
            <input type="password" 
                   class="form-control"
                   id="password"
                   name="session[password]"
                   tabindex="2">
          </div>
          
          <input type="submit" class="btn-primary" value="Login">
        </form>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="signup-modal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;<span class="sr-only">Close</span></button>
        <h4 class="modal-title">Welcome to MonkeyScripts. Hang up your coat and make yourself at home. We have snacks!</hr>
      </div>
      <div class="modal-body">
        
        <form action="<%= api_users_url %>" id="signup-form" method="POST">
          <div class="form-alert"></div>
          <input type="hidden"
                 name="authenticity_token"
                 value="<%= form_authenticity_token %>">
                 
          <div class="form-group">
            <label for="username">Username</label>
            <input type="text" 
                   class="form-control"
                   id="username"
                   name="user[username]"
                   tabindex="1">
          </div>
          
          <div class="form-group">
            <label for="username">Email</label>
            <input type="text"
                   class="form-control"
                   id="email"
                   name="user[email]"
                   tabindex="2">
          </div>
          
          <div class="form-group">
            <label for="password">Password</label>
            <input type="password"
                   class="form-control"
                   id="password"
                   name="user[password]"
                   tabindex="3">
          </div>
          <input type="submit" class="btn-primary" value="Sign Up">
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_welcome_banner.html.erb
<div class="alert alert-info">
  <button type="button" class="close" id="welcome-notice-close">&times;<span class="sr-only">Close</span></button>
  <p>Changing the world, one browser at a time.</p>
  <div class="row">
    <div class="col-md-4">
      <h3>Experience...</h3>
      <p>a whole new internet ripe for the taking.</p>
    </div>
    <div class="col-md-4">
      <h3>Find...</h3>
      <p>that perfect script for your particular needs.</p>
    </div>
    <div class="col-md-4">
      <h3>Create...</h3>
      <p>your vision with our resources and tools.</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MonkeyScripts</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <script>
    window.current_user_id = <%= current_user ? current_user.id : nil %>
  </script>
</head>
<body>
  <div class="header">
    <%= render partial: "layouts/header" %>
  </div>
  <div class="container">
    <% unless cookies["_MonkeyScripts_welcomewindow"] == "0" %>
      <%= render partial: "layouts/welcome_banner" %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/simple.html.erb
<%= yield %>